name: Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'main'

jobs:
  pytest:
    name: pytest_on_github_actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          some_other_variable: foobar
          directory: .
          file_name: .env
          fail_on_empty: false
          envkey_POSTGRES_USER: "fastapi"
          envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          envkey_POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          envkey_POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      - name: Docker set up
        run: |
          docker-compose up -d --build server db
      - name: Run Test
        run: docker-compose exec -T server pipenv run pytest